import "./globals.css";
import TiltInitializer from "./TiltInitializer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="vsc-initialized">
        <TiltInitializer />
        <div className="wrapper">
          {children}
        </div>
      </body>
    </html>
  );
}