import "./globals.css";
import TiltInitializer from "./TiltInitializer";
// src/app/global.css 또는 layout.js 에서
import 'react-quill-new/dist/quill.snow.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="vsc-initialized">
        <TiltInitializer />
        {children} 
      </body>
    </html>
  );
}